use printpdf::*;
use std::io::BufWriter;

use crate::errors::{AppError, AppResult};
use crate::models::receipt::ReceiptData;

/// Generates a PDF receipt and returns the raw bytes.
pub fn generate_receipt_pdf(data: &ReceiptData) -> AppResult<Vec<u8>> {
    let (doc, page1, layer1) = PdfDocument::new(
        format!("Receipt {}", data.receipt_id),
        Mm(210.0),
        Mm(297.0),
        "Layer 1",
    );

    let page = doc.get_page(page1);
    let layer = page.get_layer(layer1);

    let font = doc
        .add_builtin_font(BuiltinFont::HelveticaBold)
        .map_err(|e| AppError::internal_with_message(format!("PDF font error: {e}")))?;
    let font_regular = doc
        .add_builtin_font(BuiltinFont::Helvetica)
        .map_err(|e| AppError::internal_with_message(format!("PDF font error: {e}")))?;

    // Title
    layer.use_text("TIP RECEIPT", 22.0, Mm(20.0), Mm(270.0), &font);

    // Divider line
    layer.add_line_break();

    let mut y = 250.0_f64;
    let label_x = 20.0_f64;
    let value_x = 90.0_f64;
    let line_height = 10.0_f64;

    let rows: &[(&str, String)] = &[
        ("Receipt ID:", data.receipt_id.to_string()),
        ("Tip ID:", data.tip_id.to_string()),
        ("Creator:", data.creator_username.clone()),
        ("Network:", data.network.clone()),
        ("Transaction:", truncate_hash(&data.transaction_hash)),
        ("Amount (XLM):", data.amount_xlm.clone()),
        (
            "Tax Rate:",
            data.tax_rate
                .map(|r| format!("{:.2}%", r * 100.0))
                .unwrap_or_else(|| "N/A".to_string()),
        ),
        (
            "Tax Amount:",
            data.tax_amount
                .clone()
                .unwrap_or_else(|| "N/A".to_string()),
        ),
        ("Total (XLM):", data.total_amount.clone()),
        ("Issued At:", data.issued_at.format("%Y-%m-%d %H:%M UTC").to_string()),
    ];

    for (label, value) in rows {
        layer.use_text(*label, 10.0, Mm(label_x), Mm(y), &font);
        layer.use_text(value.as_str(), 10.0, Mm(value_x), Mm(y), &font_regular);
        y -= line_height;
    }

    // Footer
    layer.use_text(
        "This receipt is auto-generated by Stellar TipJar.",
        8.0,
        Mm(20.0),
        Mm(20.0),
        &font_regular,
    );

    let mut buf = BufWriter::new(Vec::new());
    doc.save(&mut buf)
        .map_err(|e| AppError::internal_with_message(format!("PDF save error: {e}")))?;

    buf.into_inner()
        .map_err(|e| AppError::internal_with_message(format!("PDF buffer error: {e}")))
}

fn truncate_hash(hash: &str) -> String {
    if hash.len() > 20 {
        format!("{}...{}", &hash[..10], &hash[hash.len() - 10..])
    } else {
        hash.to_string()
    }
}
